CREATE USER 'test'@'localhost' IDENTIFIED BY 'test123';
GRANT Usage ON *.* TO 'test'@'localhost';
GRANT Alter ON paymybuddytest.* TO 'test'@'localhost';
GRANT Create ON paymybuddytest.* TO 'test'@'localhost';
GRANT Create view ON paymybuddytest.* TO 'test'@'localhost';
GRANT Delete ON paymybuddytest.* TO 'test'@'localhost';
GRANT Drop ON paymybuddytest.* TO 'test'@'localhost';
GRANT Grant option ON paymybuddytest.* TO 'test'@'localhost';
GRANT Index ON paymybuddytest.* TO 'test'@'localhost';
GRANT Insert ON paymybuddytest.* TO 'test'@'localhost';
GRANT References ON paymybuddytest.* TO 'test'@'localhost';
GRANT Select ON paymybuddytest.* TO 'test'@'localhost';
GRANT Show view ON paymybuddytest.* TO 'test'@'localhost';
GRANT Trigger ON paymybuddytest.* TO 'test'@'localhost';
GRANT Update ON paymybuddytest.* TO 'test'@'localhost';
GRANT Alter routine ON paymybuddytest.* TO 'test'@'localhost';
GRANT Create routine ON paymybuddytest.* TO 'test'@'localhost';
GRANT Create temporary tables ON paymybuddytest.* TO 'test'@'localhost';
GRANT Execute ON paymybuddytest.* TO 'test'@'localhost';
GRANT Lock tables ON paymybuddytest.* TO 'test'@'localhost';
GRANT Grant option ON paymybuddytest.* TO 'test'@'localhost';
